### ISSUE TITLE
Support attributes in the same line as an ATX heading?

### ISSUE THREAD

**Issue by rauschma** [arobase-che/remark-attr#10]
Thanks for this plugin!

The following syntax is relatively common (Pandoc, markdown-it-attrs, etc.). It’d be great if remark-attr could support it.

```md
## My heading {#my-heading}
```

[Pandoc additionally supports](https://pandoc.org/MANUAL.html#heading-identifiers):

```md
## My heading ## {#my-heading}

My heading {#my-heading}
----------
```

**Comment by arobase-che** [comment]
Approved, will try to support it ASAP.

**Comment by rauschma** [comment]
Excellent, thanks!

[Edit: created a new issue for a question I had.]

**Comment by Eyas** [comment]
Are there any updates on this? Prettier 2.0.0 will automatically reformat:

```
## My Heading
{id=abc}
```

to

```
## My Heading

{id=abc}
```

which breaks `remark-attr`.

Supporting pandoc-style attributes will make it much easier to keep using this plugin.

**Comment by arobase-che** [comment]
I need to test it a little more. Including using Prettier 2. If you want so to see, it's on the branch `atx_inline`.

I wish I can ship it today.

**Comment by arobase-che** [comment]
Done ! :)  
0.11.0 shipped with that feature.

I wish I had update the readme but it will be for the next minor release (0.11.1).
