### ISSUE TITLE
Support spans with attributes?

### ISSUE THREAD

**Issue by rauschma** [arobase-che/remark-attr#11]
At the moment, the separate package remark-bracketed-spans supports the following syntax:

```md
This is [a span]{#id .class key=value}
```

Would it make sense to include support for spans in remark-attr? Then it would contain everything related to attributes.

The functionality of remark-bracketed-spans wouldn’t have to be reimplemented, it could just be imported and re-exported (maybe as an option, to avoid breaking existing code).

**Comment by arobase-che** [comment]
Hi, I'm late to respond but i don't think it's a good idea.

`remark-bracketed-spans` and `remark-attr` work differently.

What I think that would be nice is that remark-bracketed-span used `md-attr-parser` so the attributes will be parsed the same way (that's not the case now).
