### ISSUE TITLE
Support for custom data attributes

### ISSUE THREAD

**Issue by cedricdelpoux** [arobase-che/remark-attr#13]
Hello, 

[Custom data attributes](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/data-*) are valid html attributes but I can't find a way to use them.

```
![](img.jpg){data-id=2}
```

should generate:

```
<img src="img.jpg" data-id="2">
```

Thank you

**Comment by arobase-che** [comment]
You are right.

I commited a fix yesterday. But I would like to make it better. An user should be able to allow attributes that start by a defined prefix.

**Comment by cedricdelpoux** [comment]
Nice ! thank you. 
Do you plan to release this soon ?

**Comment by arobase-che** [comment]
> Nice ! thank you. 
> Do you plan to release this soon ?

Yes no later than that WE. I don't want to work on it at Christmas.

**Comment by cedricdelpoux** [comment]
Of course, no rush 😊

**Comment by arobase-che** [comment]
Since it had been released in 0.10.0, I close this issue.
