### ISSUE TITLE
Support for linkReference

### ISSUE THREAD

**Issue by ngsctt** [arobase-che/remark-attr#15]
Could you add support for the [linkReference][] node? I tried forking and extending the plugin myself, but I ultimately couldn't make it work.

[linkReference]: https://github.com/syntax-tree/mdast#linkreference

## The problem
The following markdown:
```markdown
[first link](http://example.com/1){hreflang="en"}   <!-- works -->
[second link][reference]{hreflang="en"}             <!-- doesn't work -->
[third link][]{hreflang="en"}                       <!-- doesn't work -->

[reference]:  http://example.com/2
[third link]: http://example.com/3
```

produces the following HTML output:
```html
<a href="http://example.com/1" hreflang="en">first link</a>
<a href="http://example.com/2">second link</a>{hreflang="en"}
<a href="http://example.com/3">third link</a>{hreflang="en"}
```

instead of:
```html
<a href="http://example.com/1" hreflang="en">first link</a>
<a href="http://example.com/2" hreflang="en">second link</a>
<a href="http://example.com/3" hreflang="en">third link</a>
```

**Comment by arobase-che** [comment]
Ok. I etudied the case.

**Comment by arobase-che** [comment]
I didn't find any trouble. In fact, it help's me support footnotes.

Now in master. Soon released.

**Comment by xsq007** [comment]
> I didn't find any trouble. In fact, it help's me support footnotes.
> 
> Now in master. Soon released.

Could you please release the latest master? Need reference-link feature.
Thanks.

**Comment by arobase-che** [comment]
Done ! ^^
