### ISSUE TITLE
Remove undefined values from hProperties

### ISSUE THREAD

**Issue by Hypercubed** [arobase-che/remark-attr#2]
I've found that if you look at the mdast generated when using `remark-attr` it includes undefined values.  This isn't a problem if you run the mdast through `remark2rehype` since it removes the `undefined` props from the HTML... but it does pollute the mdast.

See here: https://runkit.com/hypercubed/5b61cfc3fca99600122d0541

**Comment by arobase-che** [comment]
Fixed by the way ^^
