### ISSUE TITLE
There is a bug

### ISSUE THREAD

**Issue by Michael18811380328** [arobase-che/remark-attr#3]
Hello, when I use your Remark-attr I found an issue: ` let eaten = oldParser.call(self, eat, value, silent);` can't work well during build (using webpack tool in React). The error is —— call can't use. BTW, I found your codes in github are different with npm(for instance, index.js). Which is the latest version? Thank you!

**Comment by arobase-che** [comment]
Hi, :smile:  

They is some commits since the last version (which is on npm). I'm suppose to make a new version this WE.

I don't really understand your issue. Can you explain a little more ?

**Comment by Michael18811380328** [comment]
Ok, there is the issue.
At first, I use remark-attr in my project by npm install remark-attr, then there is a problem that no adequate leader. I can't fix the bug.
So I try to use index.js and write user-config by myself (it is same to default config).  The project can use in chrome. But when I build it using webpack, the code `let eaten = oldParser.call(self, eat, value, silent);` can't be built.

**Comment by arobase-che** [comment]
Hummm ... Can you try with the new version 0.7.1 please ?

**Comment by Michael18811380328** [comment]
OK, I will try the new version 0.7.1 in my project as soon as possible and contact you later. Thank you!
