### ISSUE TITLE
key/class/id support

### ISSUE THREAD

**Issue by marcelombc** [arobase-che/remark-attr#4]
Is there any reason why key/class/id attributes are not supported?

**Comment by arobase-che** [comment]
Hi,
key should work. But `class` and `id` interfere with the notation `.class` and `#id`.

They is no obvious solution for the support of class and id attributes. But it may be improved.

**Comment by arobase-che** [comment]
Ok so, now, `class` and `id` can be used. If it interferes with the notation `.class` or `#id`, the first to appear win.

So `.class1 class=class2` is `.class1`  
`class=class1 .class2` is `.class1 .class2`  
`id=id .notit` is `id`  
`.notid id=id` is `notid`

It was a `md-attr-parser` problem btw.
