### ISSUE TITLE
classes?

### ISSUE THREAD

**Issue by diomed** [arobase-che/remark-attr#6]
is adding classes possible?

`![Image](https://picsum.photos/4000/6016?image=949){:.className}`

I didn't find anything in readme.

**Comment by arobase-che** [comment]
Yes !

```md
![Image](https://picsum.photos/4000/6016?image=949){.className}
```
Without colon ^^

I really should improve the readme about that. In fact, it's based on [md-attr-parser](/arobase-che/md-attr-parser) where the syntax is better documented.
