### ISSUE TITLE
remark-attr@0.8.2 npm package missing dist/index.js file

### ISSUE THREAD

**Issue by laysent** [arobase-che/remark-attr#8]
I have tried several registry of npm to install remark-attr package with version 0.8.2. It seems that dist/index.js file is missing, which is defined as the entry point in `package.json`.
A re-publish might be required. ;-)

**Comment by arobase-che** [comment]
Absolutely !
My bad ! I'm sorry.

Should be fine now.

**Comment by laysent** [comment]
Thanks!
